
package com.github.developermobile.sisvenda.venda;

import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author tiago
 */
public class ConsultaVendaFame extends javax.swing.JInternalFrame {

    private DefaultTableModel tableModelVenda;
    private DefaultTableModel tableModelItensVenda;
    private List<ItensVenda> itensVendas;
    private List<Venda> vendas;
    private ListSelectionModel listModelVenda;
    
    public ConsultaVendaFame() {
        initComponents();
        defineModelo();
    }

    private void defineModelo() {
        tableModelVenda = (DefaultTableModel) tbVenda.getModel();
        tableModelItensVenda = (DefaultTableModel) tbItensVenda.getModel();
        listModelVenda = tbVenda.getSelectionModel();
        listModelVenda.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                 if (!e.getValueIsAdjusting()) {
                     mostrarDetalheVenda();
                 }
            }
        });
        try {
            MaskFormatter formatterDataInicio = new MaskFormatter("##/##/####");
            ftfDataInicio.setColumns(8);
            formatterDataInicio.install(ftfDataInicio);
            
            MaskFormatter formatterDataFim = new MaskFormatter("##/##/####");
            ftfDataFim.setColumns(8);
            formatterDataFim.install(ftfDataFim);
            
            tbItensVenda.getColumnModel().getColumn(0).setPreferredWidth(400);
            tbVenda.getColumnModel().getColumn(1).setPreferredWidth(400);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void atualizaTabela() {
        java.sql.Date dataInicial = new java.sql.Date(((java.util.Date)ftfDataInicio.getValue()).getTime());
        java.sql.Date dataFinal = new java.sql.Date(((java.util.Date) ftfDataFim.getValue()).getTime());
        vendas = ServiceVenda.consultaVendaPeriodo(dataInicial, dataFinal);
        int numeroLinha = tbVenda.getRowCount();
        
        for (int i = 0; i < numeroLinha; i++) {
            tableModelVenda.removeRow(0);
        }
        
        for (int i = 0; i < vendas.size(); i++) {
            tableModelVenda.insertRow(i, new Object[]{vendas.get(i).getId(),
                vendas.get(i).getCliente().getNome(),
                vendas.get(i).getDataVenda()});
        }
    }
    
    private void mostrarDetalheVenda() {
        if (tbVenda.getSelectedRow() != -1) {
            itensVendas = vendas.get(tbVenda.getSelectedRow()).getItensVendas();
            removeItensVenda();
            for (int i = 0; i < itensVendas.size(); i++) {
                tableModelItensVenda.insertRow(i, new Object[]{itensVendas.get(i).getProduto().getNome(),
                    itensVendas.get(i).getQtde(),
                    itensVendas.get(i).getProduto().getValor(),
                    itensVendas.get(i).getProduto().getValor() * itensVendas.get(i).getQtde()});
            }
        } else {
            removeItensVenda();
        }
    }
    
    private void removeItensVenda() {
        int numeroLinha = tbItensVenda.getRowCount();
        for (int i = 0; i < numeroLinha; i++) {
            tableModelItensVenda.removeRow(0);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblDataInicio = new javax.swing.JLabel();
        ftfDataInicio = new javax.swing.JFormattedTextField();
        lblDataFim = new javax.swing.JLabel();
        ftfDataFim = new javax.swing.JFormattedTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVenda = new javax.swing.JTable();
        lbItensVenda = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbItensVenda = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Venda");
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbTitulo.setBackground(java.awt.SystemColor.activeCaption);
        lbTitulo.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setText("Consultar Venda");
        jPanel1.add(lbTitulo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblDataInicio.setText("Data Inicio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(lblDataInicio, gridBagConstraints);

        ftfDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(ftfDataInicio, gridBagConstraints);

        lblDataFim.setText("Data Fim");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(lblDataFim, gridBagConstraints);

        ftfDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(ftfDataFim, gridBagConstraints);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(btnPesquisar, gridBagConstraints);

        tbVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Data Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbVenda);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        lbItensVenda.setText("ItensVenda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(lbItensVenda, gridBagConstraints);

        tbItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Qtde", "Vlr. Unit.", "Vlr. Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbItensVenda);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if (ftfDataInicio.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Informe a data inicial!", "Erro", JOptionPane.ERROR_MESSAGE);
            ftfDataInicio.requestFocus();
        } else if (ftfDataFim.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Informe a data final!", "Erro", JOptionPane.ERROR_MESSAGE);
            ftfDataFim.requestFocus();
        } else {
            atualizaTabela();
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JFormattedTextField ftfDataFim;
    private javax.swing.JFormattedTextField ftfDataInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbItensVenda;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lblDataFim;
    private javax.swing.JLabel lblDataInicio;
    private javax.swing.JTable tbItensVenda;
    private javax.swing.JTable tbVenda;
    // End of variables declaration//GEN-END:variables
}
